######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 21 12:25:03 2013
######################################################################

QT += core gui widgets


TEMPLATE = app

TARGET = gomoku

# Input
HEADERS += mainwindow.h

FORMS += mainwindow.ui

SOURCES +=	main.cpp\
			mainwindow.cpp

OTHER_FILES += \
			LICENSE\
			README.md\
			images/gomoku.png\
			images/cross.png\
			images/circle.png

